drop table contain;
drop table likereview1;
drop table reviews;
drop table orders;
drop table products;
DROP TABLE USERS;
DROP TABLE SELLERS;
DROP TABLE CUSTOMERS;
drop index INDEX_ADDRESS;
drop table ADDRESS;
delete from user_sdo_geom_metadata where table_name = 'ADDRESS';